name_maximum: 50
email_maximum: 255
pass_minimum: 6
sizes: 50
size_default: 80
user_number: 15
remember: 1
values_item: 2
content_maximum: 140
microcop_number: 10
page_limit: 10
size_picturn: 5
resize_to_limit: [400, 400]
avt_size: 50
follow_number: 100
size_follow: 30
